### ISSUE TITLE
Wrong ID for icons

### ISSUE THREAD

**Issue by tonborzenko** [praveer-k/svg-sprite#2] opened 2019-11-28 19:53 UTC
Hello! I generate sprite on Windows with your plugin, and it working, but with wrong ids.
My code:
```
const svg = new SVGSprite('./src/svg');
svg.generate('viewtranslate')
   .write('./src/_includes/sprites/messengers.svg');
```
There is example ID:
`<view id="C:\Open Server 5.2.9\OSPanel\domains\msng.loc\src\svg\skype" viewBox="96 0 48 48"/>`

I think ID must to be only **skype**

**Comment by praveer-k** [comment] 2019-11-28 21:31
Thank you for opening the issue. This one was really an embarrassing one. I don't have a windows device to test the results on but hopefully, the issue is fixed with version 1.0.10

**Closed** 2019-11-29 21:42 UTC
